#!/usr/bin/env bash





cd ..

cp -r avg ..

cd ../avg

ST=$PWD
rm *.all
rm *.avg

cd ..
BEG=$PWD

for data in sample_*; do
    cd $data/k_scr/diffu
    for files in *.coef; do
	cat $files >> $ST/coef.all
    done
    cd $BEG
done