#!/bin/bash

#input variables
N=$2

# system variables
export LC_NUMERIC=C
SOURCE="${BASH_SOURCE[0]}"
PTH=$( dirname "$SOURCE" )
stpth=$PWD
TEMP=$PWD/template
templ=$PWD/template/*

#check if template prepared
EMPTY="0"
 [ "$(ls -A $TEMP)" ] && EMPTY="1" || EMPTY="0";
echo $EMPTY
if [ $EMPTY == "0" ]; then echo "You need to prepare template first..." ;exit; fi

#main body
echo "Gen dir tree..."

cd ./inputs/left
iterL=0
for j in ./*.xyz ; do
    if [ $iterL -lt $N ] ; then
	mkdir $stpth/data/sample${iterL}
	cp $j $stpth/data/sample${iterL}/left.in
	cp ${templ} $stpth/data/sample${iterL}/
	sed -i 's/SAMPLE/s'$iterL'/' $stpth/data/sample${iterL}/run_sim
    fi
    ((iterL++))
done	#skonczylem wszystkie stech.xyz
    #musze dorobic do N?
if [ $iterL -lt $N ]; then
    nr_stech=$iterL
    repeat=`awk -v n=$N -v d=$iterL 'BEGIN{printf "%1.0d", n/d }'`
    
    for (( k=0; k<$repeat; k++ )); do
	for j in ./*.xyz ; do
	    if [ $iterL -lt $N ] ; then
		mkdir $stpth/data/sample${iterL}
		cp $j $stpth/data/sample${iterL}/left.in
		cp ${templ} $stpth/data/sample${iterL}/
		sed -i 's/SAMPLE/s'$iterL'/' $stpth/data/sample${iterL}/run_sim
	    fi
	    ((iterL++))
	done	#skonczylem wszystkie stech.xyz
    done
fi

cd $stpth/inputs/right
iterR=0
for j in ./*.xyz ; do
    if [ $iterR -lt $N ] ; then
	cp $j $stpth/data/sample${iterR}/right.in
    fi
    ((iterR++))
done	#skonczylem wszystkie stech.xyz
    #musze dorobic do N?
if [ $iterR -lt $N ]; then
    nr_stech=$iterR
    repeat=`awk -v n=$N -v d=$iterR 'BEGIN{printf "%1.0d", n/d }'`
    for (( k=0; k<$repeat; k++ )); do
	for j in ./*.xyz ; do
	    if [ $iterR -lt $N ] ; then
		cp $j $stpth/data/sample${iterR}/right.in
	    fi
	    ((iterR++))
	done	#skonczylem wszystkie stech.xyz
    done
fi

cd $stpth/data
echo "iter/ repeat: ("$repeat"+1)*"$nr_stech"="$iterL"/"$iterR
nr_dir=`ls -l | grep -v ^l | wc -l`
echo "nr dir/ nr stech: ("$nr_dir"-1)="$N
cd $stpth

