#!/usr/bin/env bash

echo "gen bins $1 $2 $3..."
FILE="${BASH_SOURCE[0]}"
SOURCE="$(dirname "$FILE")"
#echo $FILE $SOURCE

rm *.step

for data in sample*; do
    echo $data
    cd $data
#    cp -u -p $ST/gen_bin.py .
    $SOURCE/gen_bin.py $1 $2 $3
    cd ..
done
