#!/usr/bin/env bash

MY_PTH=$PWD
rm *.coef
rm *.vel

cd ..
rm *.tmp
for i in *.avg; do
    echo $i
    nazwa=${i%%.avg}
    files=`$MY_PTH/diff.py $i`
#    $MY_PTH/diff.py $i
    for j in $files; do
	ext=${j%%.tmp}
	out=${nazwa}"."${ext}
	mv $j $MY_PTH/$out
    done
done

cd $MY_PTH