#!/usr/bin/env bash

ST=$PWD
WORK_PTH=`cat SRC_PTH | head -1`
SRC_PTH="$ST/scripts"

to_do(){
#    echo "arg: " $1
    if [ $1 -eq 0 ]; then
	cd $WORK_PTH
	$SRC_PTH/gen_bin $2 $3 $4
	cd $ST
    elif [ $1 -eq 1 ]; then
	cd $WORK_PTH
	$SRC_PTH/average
	cd $ST
    elif [ $1 -eq 2 ]; then
#	cp -R -u -p $SRC_PTH/diffu $WORK_PTH
	mkdir $WORK_PTH/diffu
	cd $WORK_PTH/diffu
	$SRC_PTH/call_diff
	cd $ST
    fi

}

#cd ..

to_do $1 $2 $3 $4

#cd $ST
